name: battleships_hit
namespace: ""
runtime: quarkus
image: quay.io/ilawson/battleships_hit
imageDigest: ""
trigger: events
builder: quay.io/boson/faas-quarkus-jvm-builder
builderMap:
  default: quay.io/boson/faas-quarkus-jvm-builder
  jvm: quay.io/boson/faas-quarkus-jvm-builder
  native: quay.io/boson/faas-quarkus-native-builder
envVars:
  TESTENV: "example env"
