apiVersion: sources.knative.dev/v1beta1
kind: PingSource
metadata:
  name: heartbeat-source
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"message": "Heartbeat"}'
  sink:
    ref:
      # Deliver events to Broker.
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
