name: receiver
namespace: ""
runtime: go
image: quay.io/ilawson/func1receiver:latest
imageDigest: ""
trigger: events
builder: default
builderMap:
  default: quay.io/boson/faas-go-builder
envVars:
  TELEGRAM_API_KEY: 1558547650:AAHUZY0Row0xiF5aDn1s8L6Fwf7WJ3jAMPQ
